Bumps widestring to v1 and makes sure we pass it an aligned ptr
arcnmx/ddc-winapi-rs pull request #3
Opened 2022-11-15 02:16 UTC by jesdazrez

Hey there!

Following up after https://github.com/arcnmx/ddc-winapi-rs/pull/1, this time I kept the changes to a minimum, so just the dep bump (this time to v1 🎉) and now properly checking the ptr we pass to WideCStr::from_ptr_str is aligned.

2022-11-19 18:28 UTC, arcnmx requested changes
I'm glad we're finally addressing and cleaning this part up! Just leaving some comments because I think we can do this in a safer way.

The main thing I'm unsure of is whether the `szPhysicalMonitorDescription: [u16;128]` string is guaranteed to be nul-terminated (so we can use `WideCStr::from_slice_truncated().unwrap()` and know it will never fail), or if it might be truncated if the description is >= 128 chars (so we'd have to use `WideStr`, and possibly truncate manually). Does the win32 api let you freely use `wcscpy` or do you need to worry about `wcsncpy` when strings are too long?

I'm going to get around to looking into modernizing this repo (and going through the prior cleanup PR) this week, sorry it's taken me so long.

2022-11-19 18:28 UTC, arcnmx commented on src/lib.rs
> +            wide_str.to_string_lossy()
I'm pretty sure this can just be done safely instead:

```suggestion
            let aligned = self.monitor.szPhysicalMonitorDescription;
            let wide_str = WideCStr::from_slice_truncate(&aligned).expect("do we know if winapi strings are guaranteed to be nul-terminated (thus max length 127) or not (need to use WideStr instead)?");
            wide_str.to_string_lossy()
```

2022-11-19 18:28 UTC, arcnmx commented on src/lib.rs
> +            unsafe { WideCStr::from_ptr_str(str_ptr as _) }.to_string_lossy()
We can minimize the unsafety here by using `WideCStr::from_slice_truncate(unsafe { &*str_ptr })`
(basically treat it the same as the else branch, except no need to copy to stack first to align it).

2022-11-19 18:28 UTC, arcnmx commented on examples/enum.rs
> +}
:+1:

2022-11-23 15:56 UTC, jesdazrez commented
thanks for the review! I'll get to it soonish :)

2022-12-01 23:05 UTC, jesdazrez commented
comments should be addressed now 👍

2022-12-04 03:53 UTC, arcnmx commented
Perfect, thanks!

2022-12-04 03:54 UTC, merged